name: Merge Schedule
on:
  push:
    pull_request:
      - types:
          - opened
          - edited
  schedule:
    # https://crontab.guru/every-hour
    - cron: 0 * * * *

jobs:
  merge_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: "npm ci"
      - run: "npm run build"
      - uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
